In [1]:
import logging
from pymatgen.ext.matproj import MPRester
import numpy as np

In [6]:
from pymatgen.io.cif import Structure

s = Structure.from_file('../chemheuristics/gitData/testCry1.cif')

In [4]:
from robocrys import StructureCondenser, StructureDescriber

In [2]:
# key="Q0tUKnAE52sy7hVO"
# # Get a structure from the materials project
# a = MPRester(key)
# struct = a.get_structure_by_material_id('mp-1143')

In [12]:
condenser = StructureCondenser()
describer = StructureDescriber()

condensed_structure = condenser.condense_structure(s)
# description = describer.describe(condensed_structure)

/home/sasan/miniconda3/envs/PMG/lib/python3.9/site-packages/pymatgen/analysis/local_env.py:4137: UserWarning: No oxidation states specified on sites! For better results, set the site oxidation states in the structure.
  warnings.warn(
/home/sasan/miniconda3/envs/PMG/lib/python3.9/site-packages/pymatgen/analysis/local_env.py:3940: UserWarning: CrystalNN: cannot locate an appropriate radius, covalent or atomic radii will be used, this can lead to non-optimal results.
  warnings.warn(


In [21]:
atomIndex=0

In [98]:
robocrys_nn_dists = np.unique(np.sort([round(val[0],4) for val in condensed_structure['distances'][atomIndex].values()]))

In [368]:
Nnn_distances = list(condensed_structure['nnn_distances'][atomIndex].values())
Nnn_distances=[list(distance.values()) for distance in Nnn_distances]

r = []
for ttt in nnn_distances:
    for tt in ttt:
        for t in tt:
            r.append(t)
robocrys_Nnn_distances = np.unique(np.sort(np.round(np.array(r),4)))

In [372]:
angles_list = list(condensed_structure['angles'][atomIndex].values())
angles_list=[list(angles.values()) for angles in angles_list]

y = []
for ttt in angles_list:
    for tt in ttt:
        for t in tt:
            y.append(t)
robocrys_angles = np.unique(np.sort(np.round(np.array(y),4)))

#### ChemEnv data 

In [373]:
# !ls ../chemheuristics/gitData/

In [46]:
testCrys = np.load("../chemheuristics/gitData/testCrystalFeats.npy",allow_pickle=True)

In [64]:
chemenv_nn_dists = np.unique(np.sort([round(dist[0],4) for dist in testCrys[1]['feats'][atomIndex]['NN_distances']]))

array([2.4094, 2.4701, 2.5087, 2.5332, 2.7199, 2.7492, 2.9647, 3.0214])

In [104]:
chemenv_Nnn_dists = np.unique(np.sort([round(dist[0],4) for dist in testCrys[1]['feats'][atomIndex]['poly_distances']]))

In [268]:
angles_list2 = testCrys[1]['feats'][atomIndex]['connectivity_angles']

z = []
for angleAtom in angles_list2:
    for angle in angleAtom[1:]:
        try:
            z.append(angle[0])
        except KeyError:
            print('wrong data type')
            continue

chemenv_angles = np.unique(np.sort(np.round(np.array(z),4)))

### compare

In [383]:
def featureSummary(structure, ChemEnvFeats):
    condenser = StructureCondenser()
#     describer = StructureDescriber()
    condensed_structure = condenser.condense_structure(structure)
    for atomIndex in range(len(structure)):
        robocrys_nn_dists = np.unique(np.sort([round(val[0],4) for val in condensed_structure['distances'][atomIndex].values()]))
        Nnn_distances = list(condensed_structure['nnn_distances'][atomIndex].values())
        Nnn_distances=[list(distance.values()) for distance in Nnn_distances]

        r = []
        for ttt in nnn_distances:
            for tt in ttt:
                for t in tt:
                    r.append(t)
        robocrys_Nnn_distances = np.unique(np.sort(np.round(np.array(r),4)))
        
        angles_list = list(condensed_structure['angles'][atomIndex].values())
        angles_list=[list(angles.values()) for angles in angles_list]

        y = []
        for ttt in angles_list:
            for tt in ttt:
                for t in tt:
                    y.append(t)
        robocrys_angles = np.unique(np.sort(np.round(np.array(y),4)))
        
#         ==================================
        
        chemenv_nn_dists = np.unique(np.sort([round(dist[0],4) for dist in testCrys[1]['feats'][atomIndex]['NN_distances']]))
        chemenv_Nnn_dists = np.unique(np.sort([round(dist[0],4) for dist in testCrys[1]['feats'][atomIndex]['poly_distances']]))
        
        angles_list2 = testCrys[1]['feats'][atomIndex]['connectivity_angles']

        z = []
        for angleAtom in angles_list2:
            for angle in angleAtom[1:]:
                try:
                    z.append(angle[0])
                except KeyError:
                    print('wrong data type')
                    continue

        chemenv_angles = np.unique(np.sort(np.round(np.array(z),4)))
        
#         =================================
        if np.all(robocrys_nn_dists == chemenv_nn_dists):
            print('neighbor atom distances match for atom index', atomIndex)
        if np.all(robocrys_Nnn_distances ==chemenv_Nnn_dists):
            print('neighbor polyhedra distances match for atom index', atomIndex)
        
        if np.all(robocrys_angles.shape==chemenv_angles.shape):
            if np.all(robocrys_angles==chemenv_angles):
                print('angles match for atom index', atomIndex)
        else:
            if len(robocrys_angles) == len(chemenv_angles)+1:
                for ang in range(len(robocrys_angles)):
                    if np.all(np.delete(robocrys_angles, ang)==chemenv_angles):
                        print('angles almost match for atom index', atomIndex, 'with a missing angle')

    return                        

        


In [384]:
featureSummary(s,testCrys[1])

/home/sasan/miniconda3/envs/PMG/lib/python3.9/site-packages/pymatgen/analysis/local_env.py:4137: UserWarning: No oxidation states specified on sites! For better results, set the site oxidation states in the structure.
  warnings.warn(
/home/sasan/miniconda3/envs/PMG/lib/python3.9/site-packages/pymatgen/analysis/local_env.py:3940: UserWarning: CrystalNN: cannot locate an appropriate radius, covalent or atomic radii will be used, this can lead to non-optimal results.
  warnings.warn(


wrong data type
wrong data type
neighbor atom distances match for atom index 0
neighbor polyhedra distances match for atom index 0
angles almost match for atom index 0 with a missing angle


KeyError: 1

In [101]:
robocrys_nn_dists == chemenv_nn_dists

array([ True,  True,  True,  True,  True,  True,  True,  True])

In [371]:
robocrys_Nnn_distances ==chemenv_Nnn_dists

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True])

In [336]:
if np.all(robocrys_angles.shape==chemenv_angles.shape):
    if np.all(robocrys_angles==chemenv_angles):
        print('angles match')
else:
    if len(robocrys_angles) == len(chemenv_angles)+1:
        for ang in range(len(robocrys_angles)):
            if np.all(np.delete(robocrys_angles, ang)==chemenv_angles):
                print('angles almost match with 1 missing value')

angles almost match with 1 missing value
